server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location = /apk {
        proxy_pass https://mj-matka.s3.ap-south-1.amazonaws.com/app-universal-release.apk;
        proxy_set_header Host mj-matka.s3.ap-south-1.amazonaws.com;

        add_header Content-Type application/vnd.android.package-archive;
        add_header Content-Disposition "attachment; filename=app-release.apk";
    }
}
