@Library('Shared') _
pipeline {
    agent any
    
    parameters {
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Validate Parameters") {
            steps {
                script {
                    if (params.BACKEND_DOCKER_TAG == '') {
                        error("BACKEND_DOCKER_TAG must be provided.")
                    }
                }
            }
        }

        stage("Workspace Cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script {
                    git credentialsId: 'Github-Cred', url: 'https://github.com/MaccoTechgit/Matka-Fronted.git', branch: 'himanshu'
                }
            }
        }
        
        stage("Verify: Docker Image Tags") {
            steps {
                script {
                    echo "Using BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        
        stage("Update: Kubernetes Manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            #!/bin/bash
                            sed -i 's|image: saurav547/matka-backend:.*|image: saurav547/matka-backend:${params.BACKEND_DOCKER_TAG}|' backend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Commit & Push Updates") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-Cred', gitToolName: 'Default')]) {
                        sh '''
                            #!/bin/bash
                            git config --global user.email "sauravgarg5922@gmail.com"
                            git config --global user.name "sauravgarg547"

                            echo "Checking repository status..."
                            git status
                            
                            echo "Adding changes..."
                            git add kubernetes/backend.yaml
                            
                            echo "Committing changes..."
                            git commit -m "Updated backend image tag to ${BACKEND_DOCKER_TAG}" || echo "No changes to commit"
                            
                            echo "Pushing changes..."
                            git push origin himanshu
                        '''
                    }
                }
            }
        }
    }
    
    post {
        success {
            script {
                emailext attachLog: true,
                from: 'sauravgarg5922@gmail.com',
                subject: "Matka Backend Application Deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <h3 style="color: green;">Matka Backend Deployment Success</h3>
                        <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                        <p><strong>Build URL:</strong> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                    </body>
                    </html>
                """,
                to: 'sauravgarg5922@gmail.com, sumit.in9625@gmail.com'
                mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                from: 'sauravgarg5922@gmail.com',
                subject: "Matka Backend Deployment Failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <h3 style="color: red;">Matka Backend Deployment Failed</h3>
                        <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                    </body>
                    </html>
                """,
                to: 'sauravgarg5922@gmail.com, sumit.in9625@gmail.com'
                mimeType: 'text/html'
            }
        }
    }
}
