apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: matka
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: saurav547/matka-backend:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "256Mi" # Minimum memory the pod will request
              cpu: "200m"
            limits:
              memory: "512Mi" # Maximum memory the pod can use
              cpu: "500m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: matka
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      nodePort: 31100
