apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: matka
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1   # Ek extra pod create hoga update ke time
      maxUnavailable: 1 # Ek pod tak unavailable ho sakta hai update ke time
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-deployment
          image: saurav547/matka-backend:latest
          ports:
            - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:  # Ensure service is ready before sending traffic
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:   # Restart pod if it becomes unresponsive
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: matka
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
