apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: matka
  labels:
    app: backend
spec:
  replicas: 2  # Scale accordingly
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: saurav547/matka-backend:v1.4
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: matka
spec:
  type: LoadBalancer  # LoadBalancer for cloud-based production
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
