apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: matka
data:
  DEFAULT_DB_URI: "mongodb://kalyandadmin:kalyand123@mongo-headless-service.jannat-admin.svc.cluster.local:27017/kalyandapp?authSource=admin"
