apiVersion: apps/v1
kind: Deployment
metadata:
  name: jannat-frontend-deployment
  namespace: jannat-admin 
  labels:
    app: frontend
spec:
  replicas: 2  # HPA will handle scaling
  selector:
    matchLabels:
      app: jannat-frontend
  template:
    metadata:
      labels:
        app: jannat-frontend
    spec:
      containers:
        - name: jannat-frontend
          image: saurav547/jannat-frontend-admin-prod:v1.2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "300m"      # Minimum guaranteed CPU
              memory: "512Mi"  # Minimum guaranteed RAM
            limits:
              cpu: "600m"      # Max CPU per pod
              memory: "768Mi"  # Max RAM per pod

         
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jannat-admin 
spec:
  type: NodePort 
  selector:
    app: jannat-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31002
