apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: matka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: matka-frontend
        image: saurav547/matka-frontend:v1.3
        ports:
        - containerPort: 3000
        
