apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: matka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: matka-app
          ports:
            - containerPort: 27017
          resources:   # ✅ Add CPU requests & limits
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc



---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: matka
spec:
  type: LoadBalancer   # Agar external access chahiye
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001  # Custom NodePort, optional
      protocol: TCP
