apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: matka
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    storageClassName: mongodb-storage
  hostPath:
    path: /data/db
