apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: matka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storage  # Must match with PV's storageClassName
  resources:
    requests:
      storage: 5Gi
