apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: matka  # ✅ PVC me namespace hona chahiye
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-storage  # ✅ Same as PV
  resources:
    requests:
      storage: 10Gi
