apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: matka  # ✅ PVC me namespace hona chahiye
  labels:
    argocd.argoproj.io/managed-by: ignore  # ArgoCD will ignore this PVC
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-storage  # ✅ Same as PV
  resources:
    requests:
      storage: 10Gi
