apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: matka 
type: Opaque
data:
  MONGO_USER: a2FseWFuZGFkbWlu  # base64 encoded 'kalyandadmin'
  MONGO_PASSWORD: a2FseWFuZDEyMw==  # base64 encoded 'kalyand123'
