apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: matka
type: Opaque
data:
  MONGO_USER: a2FseWFuZGFkbWluCg==  # base64 encoded 'kalyandadmin'
  MONGO_PASSWORD: a2FseWFuZDEyMwo=  # base64 encoded 'kalyand123'
