apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: matka
type: Opaque
data:
  MONGO_USER: a2FseWFuZGJvc3NhZG1pbgo=  # base64 encoded 'kalyandbossadmin'
  MONGO_PASSWORD: a2FseWFuZGJvc3NhZG1pbjEyMwo=  # base64 encoded 'kalyand123'
