apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kalyandboss-storage-class
  namespace: matka  # Namespace where this storage class will be associated
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
